---
title: "Syllabus"
output: html_document
---

---
title: "psych 5355: personality and social development"
author: 
date: 
output: html_document
---
<br>  

**Instructor**: Joshua Jackson  
**Office**: 315B  
**Office hours**: 10-11 Wednesday and by appointment  


<br>  

#### Course Description#### 

This seminar examines how individual differences develop over the lifespan. Or, in other words, how we become who we are. The scope of the class covers a multitude of individual differences constructs (e.g., happiness, IQ, psychopathology), but a particular focus will be on personality traits. Questions that will be examined include: How early in the lifespan does one’s personality emerge? How much do parents matter in shaping who you become? Does your personality change across the lifespan? Readings will cover theories of development at different life stages and empirical research from childhood to older adulthood.  

###Course Requirements:
1.	Reading summaries.  Respond to the thought question of the week and integrate at least one of the weekly readings into your response. Email your response to Josh prior to class. Length should be ~ 1 page double spaced. 

2.	Participation. It is important to have completed all of the readings before the class period. Participation during each class period is mandatory.  

3.	Final presentation and paper. Note: You need to meet with me to have the final project idea and paper approved. Final topic MUST be approved by Spring break. The final paper is an NSF style proposal (short, two pages, very direct) that identifies a research question and outlines a study that you would like to run. 

As part of the final paper you will give an in class presentation. The presentation will consist of an overview and discussion of a reading of your choosing and a description of your proposed study. The article should provide some background information (e.g., theory, design) to facilitate the description of your project.  

My hope with these projects is that many of you could turn your final project into a paper suitable for publication. Depending on your research question, I may already have access to datasets that could address your question. 


Grading:
25% Summary comments 
25% Participation.
50% Final paper and presentation.

<br>

###Course Schedule

1. Week 1 	Intro
  - no readings

<br>
<br>

2. Week 2. Developmental questions and methods of analysis
  - McAdams & Olsen Annual Review of Psych 2010  
   
   <br>
   **Thought question**: Address the following questions: Are you the same now as you have been in the past? What characteristics of yours changed compared to those that stayed the same? 
   
<br>


3. Childhood (when does personality emerge and does it matter?)  
    + Caspi et al., 2016, Nature  
    + Deary et al., 2004 JPSP  
    + Fraley et al., 2013 Developmental Psychology  
  
  <br>
  
   **Thought question**: Do you think you will be the same in the future? What characteristics do you have now that will most impact your future self? 

<br>
<br>

4. Childhood (Do early experiences shape who we are?)  
    + Turkheimer Annual Review of Psychology  
    
   **Thought question**: Based on the reading, why do you think there is no shared environmental variance for personality traits? Do you think that other characteristics, such as IQ or vocational interests, would show shared environmental effects? 

<br>
<br>
  

5. Childhood/adolescence/adult interventions (Can you intervene and change someone? Would you want to?)    

    + Roberts et al., in press, Psych Bull
    + Sander et al., in press, Journal of Personality
    + Heckman et al., 2013, American Economics Review (ignore section II - Methodology)

   **Thought question**: Based on the readings, what would a personality intervention look like if you designed it? What characteristics would you want to change? How would you go about doing it? Is there any other concerns you want to think about? --ethics, difficulties, scaling, cost, etcetera?   
   
<br>
<br> 
6. Adolescence (How do you navigate the storm and stress of adolescence?)  
    
        + Meeus et al., Adolescent Identity Formation  
        + Cohen et al., When Is an Adolescent an Adult?  
        + Soto et al., The Developmental Psychometrics of Big Five  
   
   **Thought question**: Discuss your adolescent experience through the lens of an Eriksonian. What flaws may you have with this type of model? 

<br>
<br>
7. Adulthood (What types of experiences change personality?)  
  - Bleidorn et al,. PS 2013 Personality around the world  
  - Hutteman et al., JPSP 2015 Wherever I may roam  
  - van Scheppingen et al., 2016 Transition to parent hood (just skim)  
  
   **Thought question**: What important individaul differences are not assessed in these studies? What characteristics would you want to know change due to the life events discussed in the articles? 

<br>
<br>
8. Cognitive Ability  
  - Tucker-Drob & Briley Psych Bull 2014    
  - Richie et al Intelligence 2016  
  - Luchetti et al Journal of Gerontology 2016  
   
   **Thought question**: Describe a good follup study to one of the readings for this week. What questions are unanswered? What type of data would you need to answer your question. What difficulties would you have in collecting the data or testing your hypothesis? 
   
<br>
<br>
9. Spring Break
  - 
   **Thought question**:
<br>
<br>
10. Romantic relationships 
  - 
   **Thought question**:
<br>
<br>
11. Political attitudes and morality
  - 
   **Thought question**:
<br>
<br>
12. Dementia and end of life
  - 
   **Thought question**:
<br>
<br>
13. Class presentations

<br>
<br>
14. Class presentations

<br>
<br>
15. Class presentations

   


